version: 2
jobs:
  build:
    docker:
      - image: node:8.11.3
    working_directory: /opt/spreadsheet-sql
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm test
          command: npm test
  deploy:
    docker:
      - image: node:8.11.3
    working_directory: /opt/spreadsheet-sql
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: publish to npm registry
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ${HOME}/.npmrc
            npm run subscribe
workflows:
  version: 2
  build-and-npm-publish:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[\d].*/
            branches:
              ignore: /.*/
