version: 2
jobs:
  build:
    working_directory: /opt/spreadsheet-sql
    docker:
      - image: node:8.9.0
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: npm test
          command: npm test